// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HellouniverseController from "./hellouniverse_controller"
application.register("hellouniverse", HellouniverseController)

import MessagebarController from "./messagebar_controller"
application.register("messagebar", MessagebarController)

import StoryroomController from "./storyroom_controller"
application.register("storyroom", StoryroomController)

import UniverseController from "./universe_controller"
application.register("universe", UniverseController)

import StorybarController from "./storybar_controller"
application.register("storybar", StorybarController)

import ConfirmDeleteController from "./confirm-delete_controller"
application.register("confirm-delete", ConfirmDeleteController)

import StoryroomCharactersController from "./storyroom-characters_controller"
application.register("storyroom-characters", StoryroomCharactersController)

import StoryroomIndexController from "./storyroom-index_controller"
application.register("storyroom-index", StoryroomIndexController)

import StoryroomNewCharactersController from "./storyroom-new-characters_controller"
application.register("storyroom-new-characters", StoryroomNewCharactersController)
